### ISSUE TITLE
Additional callbacks

### ISSUE THREAD

**Issue by m039** [ragnor-rs/visum#38]
У меня была такая необходимость, передаю id объекта во фрагмент и хотелось бы достать сервис сразу после инжектирования, чтобы потом с помощью сервиса скачать объект из сети. Может быть добавить событие onInjected?

**Comment by ragnor-rs** [comment]
а можешь в жире эту задачу поставить, чтобы на планировании не забыли?

**Comment by m039** [comment]
Ну я написал здесь

**Comment by ragnor-rs** [comment]
рискуешь)

**Comment by ragnor-rs** [comment]
таск уехал в джиру
